import { standardPair } from "./";

export interface Pokémon{
  abilities:{
    ability: standardPair
    is_hidden:boolean;
    slot:number;
  }[];
  cries:{
    latest:string;
    legacy:string;
  }
  forms:standardPair[]
  game_indices:{
    game_index:number;
    version:standardPair;
  }[];
  height:number;
  held_items:{
    item:standardPair;
    version_details:{
      rarity:number;
      version:standardPair;
    }[]
  }[];
  id:number;
  is_default:boolean;
  location_area_encounters:string;
  moves:{
    move:standardPair;
    version_group_details:{
      level_learned_at:number;
      move_learn_method:standardPair;
      version_group:standardPair;
    }
  }[];
  name:string;
  order:number;
  past_abilities:{
    abilities:{
      ability: standardPair
      is_hidden:boolean;
      slot:number;
    }[];
    generation:standardPair;
  }[];
  past_types:{
    generation:standardPair;
    types:{
      slot:number;
      type:standardPair;
    }[];
  }[];
  species:standardPair;
  sprites:{
    back_default?:string;
    back_female?:string;
    back_shiny_default?:string;
    back_shiny_female?:string;
    front_default?:string;
    front_female?:string;
    front_shiny_default?:string;
    front_shiny_female?:string;
    other:{
      dream_world:{
        front_default?:string;
        front_female?:string;
      }
      home:{
        front_default?:string;
        front_female?:string;
        front_shiny_default?:string;
        front_shiny_female?:string;
      }
      'official-artwork':{
        front_default?:string;
        front_shiny?:string;
      }
      showdown:{
        back_default?:string;
        back_female?:string;
        back_shiny_default?:string;
        back_shiny_female?:string;
        front_default?:string;
        front_female?:string;
        front_shiny_default?:string;
        front_shiny_female?:string;
      }
    }
  };
  stats:{
    base_stat:number;
    effort:number;
    stat:standardPair;
  }[];
  types:{
    slot:number;
    type:standardPair;
  }[];
  weight:number;
}