import { standardPair } from "./standardPair"

export interface TypeI {
  damage_relations:{
    double_damage_from:standardPair[];
    double_damage_to:standardPair[];
    half_damage_from:standardPair[];
    half_damage_to:standardPair[];
    no_damage_from:standardPair[];
    no_damage_to:standardPair[];
  };
  game_indices:{
    game_index:number;
    generation:standardPair;
  }[];
  generation:standardPair;
  id:number;
  move_damage_class:standardPair;
  moves:standardPair[];
  name:string;
  names:{
    language:standardPair;
    name:string;
  }[];
  past_damage_relations:[];
  pokemon:{
    pokemon:standardPair;
    slot:number;
  }[];
  sprites:{
    'generation-iii':{
      colosseum:{name_icon:string};
      emerald:{name_icon:string};
      'firered-leafgreen':{name_icon:string};
      'ruby-saphire':{name_icon:string};
      xd:{name_icon:string};
    };
    'generation-iv':{
      'diamond-pearl':{name_icon:string};
      'heartgold-soulsilver':{name_icon:string};
      platinum:{name_icon:string};
    };
    'generation-ix':{ 
      'scarlet-violet':{name_icon:string}
    }
    'generation-v':{
      'black-2-white-2':{name_icon:string};
      'black-white':{name_icon:string};
    }
    'generation-vi':{
      'omega-ruby-alpha-sapphire':{name_icon:string};
      'x-y':{name_icon:string};
    }
    'generation-vii':{
      'lets-go-pikachu-lets-go-eevee':{name_icon:string};
      'sun-moon':{name_icon:string};
      'ultra-sun-ultra-moon':{name_icon:string};
    }
    'generation-viii':{
      'brilliant-diamond-and-shining-pearl':{name_icon:string};
      'legends-arceus':{name_icon:string};
      'sword-shield':{name_icon:string};
    }
  }
}